### ISSUE TITLE
Legacy C++ Borland Class Library

### ISSUE THREAD

**Issue by jeromecc** [prometheusorg/epiClassifier#4]
> // Borland Class Library
> // Copyright (c) 1993, 1998 by Borland International, All Rights Reserved
> //
> //$Revision:   1.5  $
> //
> // TDate class implementation

Problems:
 * non free
 * not maintained

> Date and time (TDate, TTime)
>
> For simple needs, replace TDate and TTime by TSystemTime, if possible. We will continue to support TSystemTime, as this class is an encapsulation of SYSTEMTIME and is needed to support common controls such as TDateTimePicker.
>
> For general date and time needs, you can use the standard C-style utilities (see ctime header documentation), as well as the new utilities introduced in C++11 (see std::chrono). Should you have the need for more comprehensive utilities, then have a look at publicly available libraries, such as Boost.Date_Time

Source: https://sourceforge.net/p/owlnext/wiki/Replacing_the_Borland_C++_Class_Libraries/#date-and-time-tdate-ttime

We need to rely on a current open source library.

Should we use Boost.Date_Time @p-ameline ?

**Comment by p-ameline** [comment]
Tu es certain que c'est utilisé dans le code avec les #define Linux ?

**Comment by jeromecc** [comment]
Yes.
nsldvuti.h
nsldvuti.cpp

**Comment by jeromecc** [comment]
I don't understand why there is code from Life Line inside this classification engine. Are notions of time or date used to classify biomedical text?

**Comment by p-ameline** [comment]
Moi non plus ;-) Ce n'est pas utilisé.

C'est le mystère de l'extraction d'une fonction au sein d'un gros paquet
de code. J'imagine qu'il y a une fonction là-dedans qui est utilisé et a
entrainé l'utilisation de ce CPP... et qu'il n'était pas grave qu'il y
ait du code en trop. Dit autrement, quand ça compile et que ça tourne,
on a autre chose à faire que de vérifier si on ne pourrait pas virer des
fonctions inutiles.

En pratique, c'est au au sein d'Episodus que ce code est vivant et
évolutif. Prometheus utilise du code Episodus, et sert surtout à faire
évoluer les bases de données. Si une dynamique autre se met en place, la
question se posera de forker et de nettoyer. Mais pour l'instant, à
chaque fois que le moteur n'a pas donné les résultats souhaités, c'était
à cause des données de la base.

**Comment by jeromecc** [comment]
The code in master is building now! 👍 
GCC displays 1061 warnings (ISO C++ forbids ...) but whatever.
I will test with the database.
This code could also stay alive inside [Episodus](https://sourceforge.net/projects/episodus/) as a micro-service.
Then it would also be reusable for other pieces of software and research projects.
