### ISSUE TITLE
this ‘for’ clause does not guard

### ISSUE THREAD

**Issue by jeromecc** [prometheusorg/epiClassifier#7]
Following warning on Debian Stretch:

    nssavoir/nsvarray.cpp:963: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for (rang = 1; (iterVect  != (*i)->pEquivalentTrie->end()) && (rang < Rang); iterVect++, rang++) ;
         ^~~
In nssavoir/nsvarray.cpp:948
In function
```c++
string VecteurRechercheSelonCritere::BorneInf(int Rang)
{
	if (empty())
  	return "" ;

  int rang ;
  string sInf = string("~~~~~~~~~~~") ;
  for (IterCritere i = begin(); i != end(); i++)
  {
  	if (!(*i)->trouve)
    {
    	if (!((*i)->pEquivalentTrie->empty()))
      {
      	EquiItemVectorIter iterVect = (*i)->pEquivalentTrie->begin() ;
        for (rang = 1; (iterVect  != (*i)->pEquivalentTrie->end()) && (rang < Rang); iterVect++, rang++) ;
        	if (iterVect != (*i)->pEquivalentTrie->end())
          	if ((*(*((*iterVect)->begin()))) < sInf)
            	sInf = (*(*((*iterVect)->begin()))) ;
      }
    }
  }
  if (sInf == string("~~~~~~~~~~~"))
  	sInf = string("") ;

  return sInf ;
}
```
Is there a problem with the "for..." line?
What about the if(s) that follow?
I am at a loss about where to add braces. Any idea @p-ameline? Thanks.

**Comment by p-ameline** [comment]
C'est un warning d'indentation "potentiellement trompeuse".

Le code est bon, mais cette ligne for est autonome (d'où le ; à la fin).
Pour le dire autrement, il ne se passe rien dans la boucle for.
Il avance l'itérateur tant qu'il n'est pas à la fin et que rang est
inférieur à Rang.

A la sortie de la boucle, il ne reste plus qu'à vérifier s'il a atteint
la fin de la boucle.

Donc, en pratique, le code que tu m'as envoyé est mal indenté car le "if
(iterVect != (*i)->pEquivalentTrie->end())" est au même niveau que le
for (il n'est pas exécuté dans la boucle, mais après que la boucle est
achevée)

**Comment by jeromecc** [comment]
Thanks.
